version: 2.1

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run:
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker build -t regviz/node-xcb .
            docker tag regviz/node-xcb regviz/node-xcb:node-16
            docker push regviz/node-xcb:node-16
            docker push regviz/node-xcb:latest
