version: 2.1

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run: docker build . node-xcb:latest
